### PR TITLE
Version 1 of Precourse1 Exercises - Kindly Review

### PR DESCRIPTION
**Pull request by IndhujaRavi**

### CODE REVIEW

**Comment by samarthjj** [comment]
Nice work Indhuja, Please add Time Complexity and also comment your code.

**Comment by IndhujaRavi** [comment]
@samarthjj Should I add the time complexities as comments within the code? Should I be adding any comments other than that?

**Comment by samarthjj** [comment]
Add the Time Complexity at the top of each file. 
Add the comments to explaining your approach for each method/function you write.
You can also ping me on Slack if you have any further queries.

**Comment by IndhujaRavi** [comment]
Assignment Completed.

**Pull request closed without merging**
