### PR TITLE
Complete Pre Course 1

### PR DESCRIPTION
**Pull request by 4-legends**

### CODE REVIEW

**Review by Nandha2Tech — COMMENTED** [review]
Great Work! Kindly include TC and SC.

**Comment by Nandha2Tech** [comment]
Great Work! Kindly include TC and SC.

**Comment by 4-legends** [comment]
@Nandha2Tech  What is TC and SC?

**Comment by 4-legends** [comment]
Also, Can I close the PR once the assessment is done?

**Comment by Nandha2Tech** [comment]
Yes. PRs can be closed. TC is the time complexity and SC is the space complexity.

**Pull request closed without merging**
